apiVersion: v1
kind: Service
metadata:
  namespace: free
  name: datatransformer-service
  labels:
    app: datatransformer-service
spec:
  ports:
    - port: {{ .Values.datatransformerservice.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: datatransformer-service

