apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: free
  name: ruettel-report-queryservice-deployment
spec:
  replicas: {{ .Values.replicas.free }}
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      containers:
        - name: ruettel-report-query-service
          image: "{{ .Values.image.repository }}queryservice:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
