apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
  name: spark-pi-scheduled
  namespace: premium
spec:
  schedule: {{ .Values.analysis.schedule }}
  concurrencyPolicy: Allow # allow more than one concurrent run of the cron job
  successfulRunHistoryLimit: 1
  failedRunHistoryLimit: 3
  template:
    type: Scala
    mode: cluster
    image: "{{ .Values.image.repository }}analysis:0.1.0" #{{ .Values.image.tag }}
    imagePullPolicy: IfNotPresent
    mainClass: runAnalysisCronJob
    mainApplicationFile: "local:///opt/spark/jars/analysis.jar"
    deps:
      repositories:
        - https://jitpack.io
      packages:
        - org.apache.spark:spark-sql-kafka-0-10_2.13:3.5.0
        - com.github.kkurt:mongo-spark:main-SNAPSHOT
    sparkVersion: "3.5.0"
    sparkConf:
      spark.jars.ivy: "/tmp/ivy"
      spark.kubernetes.memoryOverheadFactor: "0.2"
    restartPolicy:
      type: Always
    volumes:
      - name: "test-volume"
        hostPath:
          path: "/tmp"
          type: Directory
    driver:
      cores: 1
      memory: "512m"
      labels:
        version: 3.5.0
      serviceAccount: spark
      volumeMounts:
        - name: "test-volume"
          mountPath: "/tmp"
      env:
        - name: MONGODB_CONNECTION_URI
          valueFrom:
            configMapKeyRef:
              name: spark-analysis-configmap
              key: MONGODB_CONNECTION_URI
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: spark-analysis-configmap
              key: KAFKA_BOOTSTRAP_SERVERS
    executor:
      cores: 1
      instances: 2
      memory: "512m"
      labels:
        version: 3.5.0
      volumeMounts:
        - name: "test-volume"
          mountPath: "/tmp"
      env:
        - name: MONGODB_CONNECTION_URI
          valueFrom:
            configMapKeyRef:
              name: spark-analysis-configmap
              key: MONGODB_CONNECTION_URI
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: spark-analysis-configmap
              key: KAFKA_BOOTSTRAP_SERVERS