apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-analysis
  namespace: premium
spec:
  type: Scala
  mode: cluster
  image: "{{ .Values.image.repository }}analysis:0.1.0"
  imagePullPolicy: IfNotPresent #Always
  mainClass: runAnalysisStream
  #mainApplicationFile: "local:///app/analysis.jar"
  mainApplicationFile: "local:///opt/spark/jars/analysis.jar"
  #arguments: ['KAFKA_BOOSTRAP_SERVERS', 'kafka-0.kafka-headless.default.svc.cluster.local:9092,kafka-1.kafka-headless.default.svc.cluster.local:9092,kafka-2.kafka-headless.default.svc.cluster.local:9092', 'TENANT_ID', 'blub', 'MONGO_CONNECTION_URI', 'mongodb://127.0.0.1:27017/ruettelreport']
  deps:
    repositories:
      - https://jitpack.io
    packages:
      - org.apache.spark:spark-sql-kafka-0-10_2.13:3.5.0
      - com.github.kkurt:mongo-spark:main-SNAPSHOT
  sparkVersion: "3.5.0"
  sparkConf:
    spark.jars.ivy: "/tmp/ivy"
    #spark.executor.memoryOverhead: "3000"
    spark.kubernetes.memoryOverheadFactor: "0.5"
  #    spark.jars.packages: "org.apache.spark:spark-sql-kafka-0-10_2.13:3.5.0"
#    "spark.kubernetes.driverEnv.KAFKA_BOOSTRAP_SERVERS": "kafka-0.kafka-headless.default.svc.cluster.local:9092,kafka-1.kafka-headless.default.svc.cluster.local:9092,kafka-2.kafka-headless.default.svc.cluster.local:9092"
#    "spark.kubernetes.executorEnv.KAFKA_BOOSTRAP_SERVERS": "kafka-0.kafka-headless.default.svc.cluster.local:9092,kafka-1.kafka-headless.default.svc.cluster.local:9092,kafka-2.kafka-headless.default.svc.cluster.local:9092"
  restartPolicy:
    type: Always
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    #coreLimit: "1200m"
    memory: "1024m"
    memoryOverhead: 2g
    labels:
      version: 3.5.0
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
    env:
      - name: MONGODB_CONNECTION_URI
        valueFrom:
          configMapKeyRef:
            name: spark-analysis-configmap
            key: MONGODB_CONNECTION_URI
      - name: KAFKA_BOOTSTRAP_SERVERS
        valueFrom:
          configMapKeyRef:
            name: spark-analysis-configmap
            key: KAFKA_BOOTSTRAP_SERVERS

  executor:
    cores: 1
    instances: {{ .Values.analysis.analysisstreaming.executor.instances }}
    memory: "1G"
    memoryOverhead: 2g
    labels:
      version: 3.5.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
    env:
      - name: MONGODB_CONNECTION_URI
        valueFrom:
          configMapKeyRef:
            name: spark-analysis-configmap
            key: MONGODB_CONNECTION_URI
      - name: KAFKA_BOOTSTRAP_SERVERS
        valueFrom:
          configMapKeyRef:
            name: spark-analysis-configmap
            key: KAFKA_BOOTSTRAP_SERVERS