import org.apache.spark.sql.types.{StringType, StructType}

object GeoJsonHelper:

  val propertiesSchema: StructType = new StructType()
    .add("alert", StringType)
    .add("cdi", StringType)
    .add("code", StringType)
    .add("detail", StringType)
    .add("dmin", StringType)
    .add("felt", StringType)
    .add("gap", StringType)
    .add("ids", StringType)
    .add("mag", StringType)
    .add("magType", StringType)
    .add("mmi", StringType)
    .add("net", StringType)
    .add("nst", StringType)
    .add("place", StringType)
    .add("rms", StringType)
    .add("sig", StringType)
    .add("sources", StringType)
    .add("status", StringType)
    .add("time", StringType)
    .add("title", StringType)
    .add("tsunami", StringType)
    .add("type", StringType)
    .add("types", StringType)
    .add("tz", StringType)
    .add("updated", StringType)
    .add("url", StringType)

  val topLevelSchema: StructType = new StructType()
    .add("id", StringType)
    .add("geometry", StringType)
    .add("type", StringType)
    .add("properties", propertiesSchema)
