apiVersion: v1
kind: Secret
metadata:
  name: free-jwt
  namespace: free
type: Opaque
stringData:
  kongCredType: "jwt"
  key: "free.ruettelreport.tech"
  algorithm: "RS256"
  secret: "dummy"
  rsa_public_key: {{.Values.kong.premiumConsumerSecret}}