apiVersion: v1
kind: Secret
metadata:
  name: free-jwt
  namespace: free
  labels:
    konghq.com/credential: jwt
    app: free-jwt
type: Opaque
stringData:
  key: "free.ruettelreport.tech"
  algorithm: "RS256"
  secret: "dummy"
  rsa_public_key: {{.Values.kong.freeConsumerSecret | toYaml | indent 2}}