apiVersion: v1
kind: Secret
metadata:
  name: premium-jwt
  namespace: premium
type: Opaque
stringData:
  kongCredType: "jwt"
  key: "premium.ruettelreport.tech"
  algorithm: "RS256"
  secret: "dummy"
  rsa_public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzA8pwZBfdurfK1oJ45HG
    8uD/VsiaVF/rq8eLv4df0KRB/UgdOV3Kk6uv5TkLHKdwYEMDlapP20SYoD88te+J
    k7XTh6Vt2ZIp65H+wgABdl41gulbOXav+Ah5qw23Z2+xWpP48UjQ6PNicTQ6XQX3
    SkjudAQ+3vR1vNtmTnPtEYr3E07V8sFRmWwWICBUIk2uo4fe++Wqi8pl04aPtMV3
    XTMX03I9lptMaMEtt6hJAMRbCEBZ3sYb4wv/1qyyJ4mBwqk8QkLsA6r2cdYM773S
    kpX6MikBrCeg1cW1iqpXd+ws7L2RHl+Gr+DCOIOIewbN0ACYY22+1Ik1wA7zCllu
    QwIDAQAB
    -----END PUBLIC KEY-----