apiVersion: v1
kind: Secret
metadata:
  name: premium-jwt
  namespace: premium
type: Opaque
stringData:
  kongCredType: "jwt"
  key: "premium.ruettelreport.tech"
  algorithm: "RS256"
  secret: "dummy"
  rsa_public_key: {{.Values.kong.premiumConsumerSecret}}