apiVersion: v1
kind: Secret
metadata:
  name: premium-jwt
  namespace: premium
  labels:
    konghq.com/credential: jwt
    app: premium-jwt
type: Opaque
stringData:
  key: "premium.ruettelreport.tech"
  algorithm: "RS256"
  secret: "dummy"
  rsa_public_key: {{.Values.kong.premiumConsumerSecret | toYaml | indent 2}}