apiVersion: v1
kind: Service
metadata:
  namespace: shared
  name: nuxt
  labels:
    app: nuxt
spec:
  ports:
    - port:  {{ .Values.nuxt.port }}
      targetPort: 3000
      protocol: TCP
      name: api-server
    - port: {{ .Values.nuxt.socketPort }}
      targetPort: 3001
      protocol: TCP
      name: socket-server
  selector:
    app: nuxt