apiVersion: v1
kind: Service
metadata:
  namespace: shared
  name: nuxt
  labels:
    app: nuxt
spec:
  ports:
    - port:  {{ .Values.nuxt.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: nuxt