apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: premium
  name: ruettel-report-datatransformer-deployment-premium
spec:
  replicas: {{ .Values.replicas.premium }}
  selector:
    matchLabels:
      app: datatransformer-service-premium
  template:
    metadata:
      labels:
        app: datatransformer-service-premium
    spec:
      containers:
        - name: datatransformer
          image: "{{ .Values.image.repository }}datatransformerservice:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: datatransformer-configmap-premium
                  key: KAFKA_BOOTSTRAP_SERVERS