apiVersion: v1
kind: Service
metadata:
  namespace: premium
  name: datatransformer-service-premium
  labels:
    app: datatransformer-service-premium
spec:
  ports:
    - port: {{ .Values.datatransformerservice.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: datatransformer-service-premium

