apiVersion: v1
kind: Secret
metadata:
  name: free-jwt
  namespace: free
type: Opaque
stringData:
  kongCredType: "jwt"
  key: "free.ruettelreport.tech"
  algorithm: "RS256"
  secret: "dummy"
  rsa_public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn0Y6XQs6g2AWJv7tjkBn
    BKEAXmnfK8P4XiehEmNxAPqlLZy0Ws8BG8tzDtWcemX1N0/2sM1gXz0uMYfs0ggz
    C25Lx9JyhN012sVR+FWh0D7epmskTGguG4NnnWrzWqbzDRLkBrEI+5SCJVnOAwJH
    KwvZKjaHVaMOWQWwCI9t0ceTGKMJdUilz46elblUySUk9bOhTGNy2gT/wLvcJS7+
    o16ONwozG/5xxfS2a1PXkZQuMiZoBRgk2+9g6sr4fU+153mXsn7i8a9OGAtaZTKO
    N9FvIwGyo8dSxYqp3hO6sMSH+F91ZQGpJKiqlSXxpHWHsUHVarHOuVuSx6nhHpIe
    eQIDAQAB
    -----END PUBLIC KEY-----