apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruettel-report-nuxt-deployment
spec:
  selector:
    matchLabels:
      app: nuxt
  replicas: {{ .Values.replicas.premium }}
  template:
    metadata:
      labels:
        app: nuxt
    spec:
      containers:
        - name: nuxt
          image: "{{ .Values.image.repository }}frontend:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
