apiVersion: v1
kind: Service
metadata:
  namespace: free
  name: query-service
  labels:
    app: query-service
spec:
  ports:
    - port: {{ .Values.queryservice.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: query-service

