prometheus:
  prometheusSpec:
    scrapeInterval: 10s
    evaluationInterval: 30s
  grafana:
    persistence:
      enabled: true  # persistence using Persistent Volumes
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default' # Configure a dashboard provider file for Kong
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        kong-dash:
          gnetId: 7424  #  https://grafana.com/dashboards/7424
          revision: 11
          datasource: Prometheus
        kic-dash:
          gnetId: 15662
          datasource: Prometheus