name: Frontend CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

permissions:
  contents: read

jobs:
  build:
    
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node / Yarn       
      uses: actions/setup-node@v4       
      with:          
        node-version: "18"          
        cache: 'yarn'
    - name: Install Dependencies and Build
      run: |          
          yarn install          
          yarn build
      working-directory: ${{ env.working-directory }}
    
